name: HW GitHubActions

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Target environment'
        required: true
        default: 'default'
        type: choice
        options:
          - default
          - test

jobs:
  selenide-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    environment: ${{ inputs.target_env }}

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Selenide tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
          CI_USERNAME: ${{ secrets.LOGIN }}
          CI_PASSWORD: ${{ secrets.PASSWORD }}
        run: ./gradlew selenideTest -Denv=${{ inputs.target_env }} -Dusername="$CI_USERNAME" -Dpassword="$CI_PASSWORD"


      - name: Copy History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages


      - name: Build Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          subfolder: selenide
          keep_reports: 20


      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true


  playwright-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    environment: ${{ inputs.target_env }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Install Playwright browsers
        run: ./gradlew playwrightInstall

      - name: Run Playwright tests
        env:
          CI_USERNAME: ${{ secrets.LOGIN }}
          CI_PASSWORD: ${{ secrets.PASSWORD }}
        run: ./gradlew playwrightTest -Denv=${{ inputs.target_env }} -Dusername="$CI_USERNAME" -Dpassword="$CI_PASSWORD"

      - name: Copy Allure History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages


      - name: Build Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          subfolder: playwright
          keep_reports: 20


      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true